trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build HotelManagement/server --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
