trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: CmdLine@2
  displayName: 'List files'
  inputs:
    script: |
      for %%f in ( "$(Build.ArtifactStagingDirectory)\*" ) do @echo %%f
