trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build server --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
